apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  namespace: cert-manager-operator
  name: cert-manager-operatorgroup
spec:
  targetNamespaces:
  - cert-manager-operator
  upgradeStrategy: Default

