kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: bluegreen
spec:
  finalizers:
    - kubernetes
---
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: istio-system
spec:
  finalizers:
    - kubernetes
---
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: cert-manager-operator
spec:
  finalizers:
    - kubernetes
