apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bookinfo_kube-resources.yaml
- virtualservice.yaml
- gateway.yaml
- passthrough_route.yaml
- destinationrules.yaml
- peerauthentication.yaml
