apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    istio: ingressgateway
  name: trafficmanager-route
  namespace: istio-ingress
spec:
  host: TM_ROUTE
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: None
    termination: passthrough
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  wildcardPolicy: None
