apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: petclinic
spec:
  gateways:
  - istio-system/petclinic-gateway
  hosts:
  - TM_ROUTE
  http:
  - route:
    - destination:
        host: spring-petclinic
        port:
          number: 8080
