apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
  - maistra.io/istio-operator
  name: default
  namespace: istio-system
spec:
  members:
  - petclinic
  - tracing-system
